### PR TITLE
Add support for VPC

### PR DESCRIPTION
**Pull request by wenyichen**

### CODE REVIEW

**Comment by fxkr** [comment]
Thank you very much for the contribution!

Unfortunately the unit test has failed. Could you please update the code to resolve this?

The problem is that the new code explicitly adds `.aws.amazon.com`, which is not correct as `${this.console}` already includes it. To give some background on why this string cannot be hardcoded there: Amazon operates multiple completely separate instances of AWS other than the "main" one you are probably used to, for example the GovCloud console is at https://console.amazonaws-us-gov.com/console/home

**Comment by wenyichen** [comment]
Ah yeah sorry about that. Fixed this one and I'll have a couple more incoming for various services. Thanks for you work!

**Comment by fxkr** [comment]
Thank you very much!

Looking forward to more!

**Comment by fxkr** [comment]
Released as version 1.0.11

**Pull request merged**
